[package]
name = "freedom-near-proof-verifier"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
publish = false

[dependencies]
borsh = "1"
near-jsonrpc-client = "=0.22.0"
near-primitives = "=0.37.0"
thiserror = "2"

[dev-dependencies]
anyhow = "1"
near-workspaces = { version = "=0.23.0", features = ["unstable"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
